[project]
name = "home-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imagehash>=4.3.2",
    "piexif>=1.1.3",
    "pillow>=11.2.1",
    "python-ffmpeg>=2.0.12",
    "videohash2>=3.2.2",
]
